// v7 — format builder. Sections:
//   1. Basic details (incl. body_clip_count and compatible angles)
//   2. Example library (creator-facing references; only after save)
//
// Removed in v7: clip selection (Section 2 in v6) and the variation builder
// (Section 3). Clips now associate to formats from the clip side, and the
// shot list is generated by the randomiser at concept-creation time.

import { useState, useEffect } from 'react';
import { api } from '../api';
import VibePicker from './VibePicker';
import MediaUpload from './MediaUpload';
import strat from '../pages/strategist/Strategist.module.css';
import styles from './FormatBuilderModal.module.css';

// v10: required_copy_type is now a multi-select with two values only.
// format_type is free text (any label the strategist wants).
const COPY_TYPES = ['single_headline', 'multi_headline'];
const COPY_TYPE_LABELS = { single_headline: 'Single Headline', multi_headline: 'Multiple Headline' };

const TIME_OF_DAY = ['morning', 'afternoon', 'evening', 'night'];
const LIGHTING    = ['natural', 'studio', 'dark'];
const LOCATION    = ['indoor', 'outdoor', 'on_the_go'];
const LOCATION_LABELS = { indoor: 'Indoor', outdoor: 'Outdoor', on_the_go: 'On the go' };

// ── Format example library ──
function ExampleLibrary({ formatId, initialExamples }) {
  // Seed from parent's already-fetched examples (if any) so the list shows
  // immediately instead of flashing empty while the dedicated GET resolves.
  const [examples, setExamples] = useState(Array.isArray(initialExamples) ? initialExamples : []);
  const [loading, setLoading] = useState(true);
  const [draft, setDraft] = useState({
    media_url: '', time_of_day: 'afternoon', lighting: 'natural', location: 'indoor', is_main: false,
  });
  const [busy, setBusy] = useState(false);

  async function refresh() {
    setLoading(true);
    try {
      const list = await api.getFormatExamples(formatId);
      console.log('[ExampleLibrary] refresh →', formatId, list.length, 'examples');
      setExamples(list);
    }
    catch (err) { console.error('[ExampleLibrary] refresh failed', err); }
    finally { setLoading(false); }
  }

  useEffect(() => { refresh(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [formatId]);

  // Auto-save the example as soon as a media URL is "committed" — i.e. a file
  // upload finishes, or the URL field blurs / Enter is pressed. Tags + main
  // flag come from the current draft values, which the user sets BEFORE
  // uploading. After save, the draft resets so the next upload can flow in.
  async function saveExample(mediaUrl) {
    console.log('[ExampleLibrary] saveExample. formatId=', formatId, 'mediaUrl=', mediaUrl);
    if (!formatId) { alert('Save the format first before adding examples.'); return; }
    if (!mediaUrl) return;
    const payload = { ...draft, media_url: mediaUrl };
    setBusy(true);
    try {
      console.log('[ExampleLibrary] POST /formats/', formatId, '/examples payload=', payload);
      const created = await api.createFormatExample(formatId, payload);
      console.log('[ExampleLibrary] POST succeeded, server returned:', created);
      if (created && created.id) {
        setExamples(prev => [created, ...prev.filter(e => e.id !== created.id)]);
      }
      await refresh();
    } catch (err) {
      console.error('[ExampleLibrary] saveExample FAILED:', err);
      alert('Failed to save example: ' + (err?.message || 'unknown error'));
    } finally {
      // Reset the add-card regardless of outcome so the user can immediately
      // try again (orphaned URL is cleared on failure too).
      setDraft({ media_url: '', time_of_day: 'afternoon', lighting: 'natural', location: 'indoor', is_main: false });
      setBusy(false);
    }
  }

  async function setMain(id) {
    setBusy(true);
    try { await api.updateFormatExample(id, { is_main: true }); await refresh(); }
    catch (err) { alert(err.message); }
    finally { setBusy(false); }
  }

  async function updateTag(id, key, value) {
    setBusy(true);
    try { await api.updateFormatExample(id, { [key]: value }); await refresh(); }
    catch (err) { alert(err.message); }
    finally { setBusy(false); }
  }

  async function remove(id) {
    if (!window.confirm('Delete this example permanently?')) return;
    setBusy(true);
    try { await api.deleteFormatExample(id); await refresh(); }
    catch (err) { alert(err.message); }
    finally { setBusy(false); }
  }

  return (
    <div className={styles.exampleLibrary}>
      <div className={styles.exampleAddCard}>
        <p className={styles.exampleAddLabel}>
          Add a new example — tag it first, then upload / paste a URL and it saves automatically.
        </p>
        <div className={styles.exampleTagRow}>
          <select
            value={draft.time_of_day}
            disabled={busy}
            onChange={e => setDraft(d => ({ ...d, time_of_day: e.target.value }))}
          >
            {TIME_OF_DAY.map(t => <option key={t} value={t}>{t}</option>)}
          </select>
          <select
            value={draft.lighting}
            disabled={busy}
            onChange={e => setDraft(d => ({ ...d, lighting: e.target.value }))}
          >
            {LIGHTING.map(t => <option key={t} value={t}>{t}</option>)}
          </select>
          <select
            value={draft.location}
            disabled={busy}
            onChange={e => setDraft(d => ({ ...d, location: e.target.value }))}
          >
            {LOCATION.map(t => <option key={t} value={t}>{LOCATION_LABELS[t]}</option>)}
          </select>
          <label className={styles.exampleMainCheck}>
            <input
              type="checkbox"
              checked={draft.is_main}
              disabled={busy}
              onChange={e => setDraft(d => ({ ...d, is_main: e.target.checked }))}
            /> Set as main
          </label>
        </div>
        <MediaUpload
          label="Video / GIF"
          url={draft.media_url}
          setUrl={(u) => setDraft(d => ({ ...d, media_url: u }))}
          onCommit={saveExample}
          disabled={busy}
        />
        {busy && <p className={styles.exampleAddLabel} style={{ marginTop: 8 }}>Saving…</p>}
      </div>

      {loading ? (
        <p className={styles.empty}>Loading examples…</p>
      ) : examples.length === 0 ? (
        <p className={styles.empty}>No examples yet.</p>
      ) : (
        <div className={styles.exampleList}>
          {examples.map(ex => (
            <div key={ex.id} className={`${styles.exampleRow} ${ex.is_main ? styles.exampleRowMain : ''}`}>
              <div className={styles.exampleThumb}>
                {/\.(gif|png|jpe?g|webp)$/i.test(ex.media_url)
                  ? <img src={ex.media_url} alt="" />
                  : <video src={ex.media_url} muted loop playsInline />}
              </div>
              <div className={styles.exampleMeta}>
                <select value={ex.time_of_day} onChange={e => updateTag(ex.id, 'time_of_day', e.target.value)}>
                  {TIME_OF_DAY.map(t => <option key={t} value={t}>{t}</option>)}
                </select>
                <select value={ex.lighting} onChange={e => updateTag(ex.id, 'lighting', e.target.value)}>
                  {LIGHTING.map(t => <option key={t} value={t}>{t}</option>)}
                </select>
                <select value={ex.location} onChange={e => updateTag(ex.id, 'location', e.target.value)}>
                  {LOCATION.map(t => <option key={t} value={t}>{LOCATION_LABELS[t]}</option>)}
                </select>
              </div>
              <div className={styles.exampleActions}>
                {ex.is_main
                  ? <span className={styles.exampleMainPill}>★ Main</span>
                  : <button type="button" className={styles.exampleSetMainBtn} onClick={() => setMain(ex.id)}>Set as main</button>}
                <button type="button" className={styles.exampleDelBtn} onClick={() => remove(ex.id)}>Delete</button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ── Hook selector — picks which active hook clips are eligible for this format ──
function HookSelector({ selectedIds, setSelectedIds }) {
  const [hooks, setHooks] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const clips = await api.getClips();
        if (!cancelled) {
          setHooks(clips.filter(c => c.is_hook && c.status === 'active'));
        }
      } finally { if (!cancelled) setLoading(false); }
    })();
    return () => { cancelled = true; };
  }, []);

  function toggle(id) {
    setSelectedIds(prev => prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id]);
  }

  const allSelected = hooks.length > 0 && selectedIds.length === hooks.length;

  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 }}>
        <p className={styles.sectionHint} style={{ margin: 0 }}>
          {loading
            ? 'Loading hooks…'
            : hooks.length === 0
              ? 'No active hook clips in the library yet.'
              : `Tap to toggle. ${selectedIds.length}/${hooks.length} selected.`}
        </p>
        {hooks.length > 0 && (
          <button
            type="button"
            onClick={() => setSelectedIds(allSelected ? [] : hooks.map(h => h.id))}
            style={{
              background: 'none', border: 'none', padding: 0, cursor: 'pointer',
              fontSize: 12, fontWeight: 600, color: '#857D70', textDecoration: 'underline',
            }}
          >
            {allSelected ? 'Deselect all' : 'Select all'}
          </button>
        )}
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(96px, 1fr))', gap: 8 }}>
        {hooks.map(c => {
          const selected = selectedIds.includes(c.id);
          const url = c.reference_url;
          const isImage = url && /\.(gif|png|jpe?g|webp|svg)(\?.*)?$/i.test(url);
          return (
            <button
              key={c.id}
              type="button"
              onClick={() => toggle(c.id)}
              title={selected ? `${c.name} (selected)` : `Select ${c.name}`}
              style={{
                position: 'relative',
                display: 'flex', flexDirection: 'column', alignItems: 'stretch',
                padding: 0, background: '#fff',
                border: selected ? '2px solid #257232' : '1px solid #E5E0D6',
                borderRadius: 6, overflow: 'hidden',
                cursor: 'pointer',
                textAlign: 'left',
              }}
            >
              <div style={{
                position: 'relative',
                width: '100%', aspectRatio: '9 / 16',
                background: '#EBE6DD',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                overflow: 'hidden',
              }}>
                {url ? (
                  isImage
                    ? <img src={url} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                    : <video src={url} autoPlay loop muted playsInline style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                ) : (
                  <span style={{ fontSize: 10, color: '#857D70' }}>No ref</span>
                )}
                {selected && (
                  <span style={{
                    position: 'absolute', top: 4, right: 4,
                    width: 22, height: 22, borderRadius: '50%',
                    background: '#257232', color: '#fff',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    fontSize: 13, fontWeight: 700,
                  }}>✓</span>
                )}
              </div>
              <p style={{
                margin: 0, padding: '4px 6px',
                fontSize: 11, fontWeight: 600,
                color: '#3a3128',
                whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
              }}>
                {c.name}
              </p>
            </button>
          );
        })}
      </div>
    </div>
  );
}

// ── Variation builder (V1–V5 arrangements, each with ordered clip items + takes) ──
function VariationBuilder({ formatId }) {
  const [structures, setStructures] = useState([]);
  const [clipPool, setClipPool] = useState([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);

  async function refresh() {
    setLoading(true);
    try {
      const [s, clips] = await Promise.all([
        api.getClipStructures(formatId),
        api.getClips(),
      ]);
      setStructures(s);
      setClipPool(clips.filter(c => c.status === 'active' && c.body_eligible !== false));
    } finally { setLoading(false); }
  }

  useEffect(() => { refresh(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [formatId]);

  const usedPositions = new Set(structures.map(s => s.position));
  const nextFreePosition = [1,2,3,4,5].find(p => !usedPositions.has(p));

  async function addArrangement() {
    if (!nextFreePosition) return;
    setBusy(true);
    try {
      await api.createClipStructure(formatId, {
        name: `V${nextFreePosition}`,
        position: nextFreePosition,
        items: [],
      });
      await refresh();
    } catch (err) { alert(err.message); }
    finally { setBusy(false); }
  }

  async function patchStructure(id, patch) {
    setBusy(true);
    try { await api.updateClipStructure(id, patch); await refresh(); }
    catch (err) { alert(err.message); }
    finally { setBusy(false); }
  }

  async function removeStructure(id) {
    if (!window.confirm('Delete this arrangement?')) return;
    setBusy(true);
    try { await api.deleteClipStructure(id); await refresh(); }
    catch (err) { alert(err.message); }
    finally { setBusy(false); }
  }

  return (
    <div>
      {loading ? (
        <p className={styles.empty}>Loading arrangements…</p>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          {structures.map(s => (
            <ArrangementEditor
              key={s.id}
              structure={s}
              clipPool={clipPool}
              busy={busy}
              onPatch={patch => patchStructure(s.id, patch)}
              onDelete={() => removeStructure(s.id)}
            />
          ))}
          {nextFreePosition && (
            <button
              type="button"
              className={styles.addExampleBtn}
              disabled={busy}
              onClick={addArrangement}
              style={{ alignSelf: 'flex-start' }}
            >
              + Add arrangement (V{nextFreePosition})
            </button>
          )}
          {structures.length === 0 && (
            <p className={styles.sectionHint}>
              No arrangements yet. Add up to 5 (V1–V5). Each is an ordered list of clips with a per-item takes count.
            </p>
          )}
          {clipPool.length === 0 && structures.length === 0 && (
            <p className={styles.sectionHint}>
              Tip: create some clips in the Clip Library first — you can pick from the full library when building arrangements.
            </p>
          )}
        </div>
      )}
    </div>
  );
}

function ArrangementEditor({ structure, clipPool, busy, onPatch, onDelete }) {
  const [name, setName] = useState(structure.name);
  const [status, setStatus] = useState(structure.status);
  const [items, setItems] = useState(structure.items || []);
  const [dragIdx, setDragIdx] = useState(null);

  // Sync local state if parent refreshes structure (e.g. after add)
  useEffect(() => {
    setName(structure.name);
    setStatus(structure.status);
    setItems(structure.items || []);
  }, [structure]);

  const usedClipIds = new Set(items.map(i => i.clip_id));

  function addClip(clipId) {
    if (!clipId || usedClipIds.has(clipId)) return;
    setItems(prev => [...prev, { clip_id: clipId, takes: 1 }]);
  }
  function removeAt(idx) {
    setItems(prev => prev.filter((_, i) => i !== idx));
  }
  function move(from, to) {
    if (to < 0 || to >= items.length || from === to) return;
    setItems(prev => {
      const next = prev.slice();
      const [picked] = next.splice(from, 1);
      next.splice(to, 0, picked);
      return next;
    });
  }

  function onDragStart(idx) { setDragIdx(idx); }
  function onDragOver(e) { e.preventDefault(); }
  function onDrop(targetIdx) {
    if (dragIdx === null) return;
    move(dragIdx, targetIdx);
    setDragIdx(null);
  }

  function lookupClip(id) {
    const found = clipPool.find(c => c.id === id);
    if (found) return found;
    return { name: '⚠️ Deleted clip — tap × to remove', reference_url: null, _missing: true };
  }

  function saveItems() {
    onPatch({
      name: name.trim() || structure.name,
      status,
      items: items.map(i => ({ clip_id: i.clip_id, takes: i.takes })),
    });
  }

  const dirty = name !== structure.name || status !== structure.status ||
    JSON.stringify(items) !== JSON.stringify(structure.items || []);

  return (
    <div style={{ border: '1px solid #E5E0D6', borderRadius: 10, padding: 12, background: '#FAF7F1' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
        <span style={{
          background: '#257232', color: '#fff', fontSize: 11, fontWeight: 700,
          padding: '2px 8px', borderRadius: 999,
        }}>V{structure.position}</span>
        <input
          className={strat.input}
          style={{ flex: 1 }}
          value={name}
          onChange={e => setName(e.target.value)}
          placeholder="Arrangement name"
        />
        <select className={strat.select} value={status} onChange={e => setStatus(e.target.value)} style={{ width: 120 }}>
          <option value="active">Active</option>
          <option value="paused">Paused</option>
          <option value="retired">Retired</option>
        </select>
        <button type="button" className={strat.cancelBtn} onClick={onDelete} style={{ color: '#b91c1c' }}>Delete</button>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 4, marginBottom: 8 }}>
        {items.length === 0 && <p className={styles.sectionHint}>No clips yet — add one below.</p>}
        {items.map((it, idx) => {
          const clip = lookupClip(it.clip_id);
          const url = clip.reference_url;
          const isImage = url && /\.(gif|png|jpe?g|webp|svg)(\?.*)?$/i.test(url);
          return (
            <div
              key={`${it.clip_id}-${idx}`}
              draggable
              onDragStart={() => onDragStart(idx)}
              onDragOver={onDragOver}
              onDrop={() => onDrop(idx)}
              style={{
                display: 'flex', alignItems: 'center', gap: 8,
                padding: '6px 8px',
                background: clip._missing ? '#FEF2F2' : '#fff',
                border: `1px solid ${clip._missing ? '#FCA5A5' : '#E5E0D6'}`,
                borderRadius: 6,
                cursor: 'grab',
              }}
            >
              <span style={{ color: '#857D70', fontWeight: 700, width: 24 }}>{idx + 1}.</span>
              <span style={{ color: '#857D70', cursor: 'grab' }}>⋮⋮</span>
              <div style={{
                width: 36, height: 64, flexShrink: 0,
                borderRadius: 4, overflow: 'hidden',
                background: '#EBE6DD',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
              }}>
                {url ? (
                  isImage
                    ? <img src={url} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                    : <video src={url} autoPlay loop muted playsInline style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                ) : (
                  <span style={{ fontSize: 9, color: '#857D70' }}>No ref</span>
                )}
              </div>
              <span style={{ flex: 1, color: clip._missing ? '#b91c1c' : 'inherit', fontWeight: clip._missing ? 600 : 400 }}>{clip.name}</span>
              <button type="button" onClick={() => move(idx, idx - 1)} disabled={idx === 0} style={{ background: 'none', border: 'none', cursor: 'pointer' }}>↑</button>
              <button type="button" onClick={() => move(idx, idx + 1)} disabled={idx === items.length - 1} style={{ background: 'none', border: 'none', cursor: 'pointer' }}>↓</button>
              <button type="button" onClick={() => removeAt(idx)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#b91c1c' }}>×</button>
            </div>
          );
        })}
      </div>

      <div style={{ marginTop: 4, marginBottom: 8 }}>
        <p className={styles.sectionHint} style={{ marginBottom: 6 }}>
          {clipPool.length === 0 ? 'No clips in the library yet.' : 'Tap a clip to add it to the arrangement:'}
        </p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(96px, 1fr))', gap: 8 }}>
          {clipPool.map(c => {
            const used = usedClipIds.has(c.id);
            const url = c.reference_url;
            const isImage = url && /\.(gif|png|jpe?g|webp|svg)(\?.*)?$/i.test(url);
            return (
              <button
                key={c.id}
                type="button"
                onClick={() => addClip(c.id)}
                disabled={used}
                title={used ? `${c.name} (already added)` : `Add ${c.name}`}
                style={{
                  position: 'relative',
                  display: 'flex', flexDirection: 'column', alignItems: 'stretch',
                  padding: 0, background: '#fff',
                  border: used ? '1px solid #D1CBC0' : '1px solid #E5E0D6',
                  borderRadius: 6, overflow: 'hidden',
                  cursor: used ? 'default' : 'pointer',
                  opacity: used ? 0.45 : 1,
                  textAlign: 'left',
                }}
              >
                <div style={{
                  width: '100%', aspectRatio: '9 / 16',
                  background: '#EBE6DD',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  overflow: 'hidden',
                }}>
                  {url ? (
                    isImage
                      ? <img src={url} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                      : <video src={url} autoPlay loop muted playsInline style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                  ) : (
                    <span style={{ fontSize: 10, color: '#857D70' }}>No ref</span>
                  )}
                  {used && (
                    <span style={{
                      position: 'absolute', top: 4, right: 4,
                      width: 22, height: 22, borderRadius: '50%',
                      background: '#257232', color: '#fff',
                      display: 'flex', alignItems: 'center', justifyContent: 'center',
                      fontSize: 13, fontWeight: 700,
                    }}>✓</span>
                  )}
                </div>
                <p style={{
                  margin: 0, padding: '4px 6px',
                  fontSize: 11, fontWeight: 600,
                  color: '#3a3128',
                  whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
                }}>
                  {c.name}
                </p>
              </button>
            );
          })}
        </div>
      </div>

      <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
        <button
          type="button"
          className={strat.saveBtn}
          onClick={saveItems}
          disabled={busy || !dirty}
        >
          {dirty ? 'Save arrangement' : 'Saved'}
        </button>
      </div>
    </div>
  );
}

// ── Main modal ──
export default function FormatBuilderModal({ format, angles, vibes, onClose, onSaved, onDeleted, onVibeCreated, onVibeDeleted }) {
  const [form, setForm] = useState({
    name: format?.name || '',
    description: format?.description || '',
    // required_copy_type is now an array (TEXT[])
    required_copy_type: Array.isArray(format?.required_copy_type)
      ? format.required_copy_type
      : (format?.required_copy_type ? [format.required_copy_type] : ['single_headline']),
    // format_type is free text
    format_type: format?.format_type || '',
    thumbnail_url: format?.thumbnail_url || '',
    status: format?.status || 'active',
    priority_weight: format?.priority_weight || 3,
  });

  function toggleCopyType(t) {
    setForm(f => {
      const has = f.required_copy_type.includes(t);
      const next = has
        ? f.required_copy_type.filter(x => x !== t)
        : [...f.required_copy_type, t];
      return { ...f, required_copy_type: next };
    });
  }
  const [angleIds, setAngleIds] = useState(format?.compatible_angle_ids || []);
  const [hookClipIds, setHookClipIds] = useState(format?.hook_clip_ids || []);
  const [vibeIds, setVibeIds] = useState(format?.vibe_ids || []);
  const [allVibes, setAllVibes] = useState(!!format?.all_vibes);
  const [saving, setSaving] = useState(false);
  const [confirmDel, setConfirmDel] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const set = k => e => setForm(f => ({ ...f, [k]: e.target.value }));

  async function remove() {
    if (!format?.id) return;
    setDeleting(true);
    try {
      const res = await api.deleteFormat(format.id);
      if (res?.retired) {
        alert("This format is referenced by existing concepts, so it was retired (status='retired') instead of deleted.");
      }
      if (onDeleted) onDeleted(format.id, res);
      onClose();
    } catch (err) { alert(err.message); setDeleting(false); }
  }

  function toggleAngle(id) {
    setAngleIds(prev => prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id]);
  }

  async function save() {
    if (!form.required_copy_type || form.required_copy_type.length === 0) {
      alert('Pick at least one required copy type'); return;
    }
    setSaving(true);
    try {
      const data = {
        ...form,
        format_type: form.format_type.trim() || null,
        priority_weight: Number(form.priority_weight),
        compatible_angle_ids: angleIds,
        hook_clip_ids: hookClipIds,
        vibe_ids: vibeIds,
        all_vibes: allVibes,
      };
      const saved = format ? await api.updateFormat(format.id, data) : await api.createFormat(data);
      onSaved(saved);
      onClose();
    } catch (err) {
      alert(err.message);
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className={strat.overlay} onClick={e => { if (e.target === e.currentTarget) onClose(); }}>
      <div className={`${strat.modal} ${styles.wide}`}>
        <p className={strat.modalTitle}>{format ? 'Edit Format' : 'New Format'}</p>

        {/* Section 1 — Basic details */}
        <section className={styles.section}>
          <h3 className={styles.sectionTitle}>1. Basic details</h3>
          <div className={strat.fieldGroup}>
            <div>
              <label className={strat.label}>Name</label>
              <input className={strat.input} value={form.name} onChange={set('name')} placeholder="Format name" />
            </div>
            <div>
              <label className={strat.label}>Description</label>
              <textarea className={strat.textarea} value={form.description} onChange={set('description')} placeholder="How is this format shot and edited?" />
            </div>
            <div>
              <label className={strat.label}>Format Type</label>
              <input
                className={strat.input}
                value={form.format_type}
                onChange={set('format_type')}
                placeholder='e.g. "Voiceover", "UGC", "Talking Head"'
              />
            </div>
            <div>
              <label className={strat.label}>Required Copy Type (pick one or both) *</label>
              <div className={strat.checkGrid}>
                {COPY_TYPES.map(t => {
                  const active = form.required_copy_type.includes(t);
                  return (
                    <button
                      key={t}
                      type="button"
                      className={`${strat.checkChip} ${active ? strat.checkChipActive : ''}`}
                      onClick={() => toggleCopyType(t)}
                    >
                      {COPY_TYPE_LABELS[t]}
                    </button>
                  );
                })}
              </div>
            </div>
            <div>
              <MediaUpload
                label="Thumbnail (shown on the format selection grid)"
                url={form.thumbnail_url}
                setUrl={(u) => setForm(f => ({ ...f, thumbnail_url: u }))}
              />
            </div>
            <div>
              <label className={strat.label}>Compatible Angles</label>
              <div className={strat.checkGrid}>
                {angles.map(a => (
                  <button
                    key={a.id}
                    type="button"
                    className={`${strat.checkChip} ${angleIds.includes(a.id) ? strat.checkChipActive : ''}`}
                    onClick={() => toggleAngle(a.id)}
                  >
                    {a.name}
                  </button>
                ))}
              </div>
            </div>
            <div>
              <VibePicker
                vibes={vibes}
                vibeIds={vibeIds}
                setVibeIds={setVibeIds}
                allVibes={allVibes}
                setAllVibes={setAllVibes}
                onVibeCreated={onVibeCreated}
                onVibeDeleted={onVibeDeleted}
              />
            </div>
            <div className={styles.gridTwo}>
              <div>
                <label className={strat.label}>Priority Weight (1–5)</label>
                <select className={strat.select} value={form.priority_weight} onChange={set('priority_weight')}>
                  {[1,2,3,4,5].map(n => <option key={n} value={n}>{n}</option>)}
                </select>
              </div>
              <div>
                <label className={strat.label}>Status</label>
                <select className={strat.select} value={form.status} onChange={set('status')}>
                  <option value="active">Active</option>
                  <option value="paused">Paused</option>
                  <option value="retired">Retired</option>
                </select>
              </div>
            </div>
          </div>
          <p className={styles.sectionHint} style={{ marginTop: 8 }}>
            Clips are managed in the Clip Library tab. Tag clips with this format there to make them eligible for the arrangements below.
          </p>
        </section>

        {/* Section 2 — Eligible hooks */}
        <section className={styles.section}>
          <h3 className={styles.sectionTitle}>2. Eligible hooks for this format</h3>
          <p className={styles.sectionHint}>
            Pick which hook clips the randomiser can use for this format. If you leave this empty, all active hooks become eligible.
          </p>
          <HookSelector selectedIds={hookClipIds} setSelectedIds={setHookClipIds} />
        </section>

        {/* Section 3 — Variation builder */}
        <section className={styles.section}>
          <h3 className={styles.sectionTitle}>3. Variation builder (V1–V5 arrangements)</h3>
          <p className={styles.sectionHint}>
            Build up to 5 ordered arrangements of clips. The randomiser picks one per variation. Takes are calculated automatically from how many variations share the same opening clips.
          </p>
          {format?.id ? (
            <VariationBuilder formatId={format.id} />
          ) : (
            <p className={styles.empty}>Save the format first, then come back to build arrangements.</p>
          )}
        </section>

        {/* Section 4 — Example library */}
        <section className={styles.section}>
          <h3 className={styles.sectionTitle}>4. Example library</h3>
          <p className={styles.sectionHint}>
            Reference videos shown to creators on the shoot phase. The one marked "main" is the default. Tag each so creators can filter.
          </p>
          {format?.id ? (
            <ExampleLibrary formatId={format.id} initialExamples={format.examples} />
          ) : (
            <p className={styles.empty}>Save the format first, then come back to add examples.</p>
          )}
        </section>

        {format?.id && (
          <div style={{ marginTop: 16, paddingTop: 16, borderTop: '1px solid #EBE6DD' }}>
            {!confirmDel ? (
              <button type="button" className={strat.cancelBtn} onClick={() => setConfirmDel(true)} style={{ color: '#b91c1c' }}>
                Delete format
              </button>
            ) : (
              <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                <span style={{ fontSize: 13, color: '#7f1d1d' }}>
                  Delete permanently? (If concepts reference it, it will be retired instead.)
                </span>
                <button type="button" className={strat.cancelBtn} onClick={() => setConfirmDel(false)}>Cancel</button>
                <button type="button" className={strat.saveBtn} onClick={remove} disabled={deleting} style={{ background: '#dc2626' }}>
                  {deleting ? 'Deleting…' : 'Yes, delete'}
                </button>
              </div>
            )}
          </div>
        )}

        <div className={strat.btnRow}>
          <button className={strat.cancelBtn} onClick={onClose}>Cancel</button>
          <button className={strat.saveBtn} onClick={save} disabled={saving}>
            {saving ? 'Saving…' : 'Save'}
          </button>
        </div>
      </div>
    </div>
  );
}
