// v17 migration — cascade clip deletes through arrangement items.
//
// clip_structure_items.clip_id was created without an ON DELETE rule, so
// deleting a clip referenced by any arrangement failed with a FK violation.
// We re-create the FK with ON DELETE CASCADE so removing a clip cleanly
// drops it from every arrangement that used it.

require('dotenv').config();
const db = require('./index');

const schema = `
BEGIN;

-- Drop the existing FK (name was auto-generated by Postgres; the catalog
-- query below finds whatever it's called).
DO $$
DECLARE
  fk_name TEXT;
BEGIN
  SELECT conname INTO fk_name
    FROM pg_constraint
   WHERE conrelid = 'clip_structure_items'::regclass
     AND contype = 'f'
     AND pg_get_constraintdef(oid) LIKE '%REFERENCES clips(%';
  IF fk_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE clip_structure_items DROP CONSTRAINT %I', fk_name);
  END IF;
END $$;

ALTER TABLE clip_structure_items
  ADD CONSTRAINT clip_structure_items_clip_id_fkey
  FOREIGN KEY (clip_id) REFERENCES clips(id) ON DELETE CASCADE;

COMMIT;
`;

(async () => {
  try {
    await db.query(schema);
    console.log('v17 migration complete.');
    console.log('   • clip_structure_items.clip_id FK now ON DELETE CASCADE');
    process.exit(0);
  } catch (err) {
    console.error('v17 migration failed:', err);
    process.exit(1);
  }
})();
